### ISSUE TITLE
Doc improvements/suggestions

### ISSUE THREAD

**Issue by aperepel** [sequenceiq/munchausen#15]
- On IP addresses - mention these are typically private network IPs for dual-homed nodes
- Explain the 2375 port (non-secure swarm), as docker machine creates TLS instances by default on 2376
- Explain/give examples for the node1, node2, ..., nodeN (basically highlight Consul IPs vs cluster nodes IPs)
- Document the `add()` command, it's already implemented ;)
- Mention that the host running the munchausen container becomes a swarm master node

**Comment by martonsereg** [comment]
Improved documentation in: https://github.com/sequenceiq/munchausen/pull/19
