### ISSUE TITLE
failed to bootstrap swarm

### ISSUE THREAD

**Issue by ylvmw** [sequenceiq/munchausen#23]
Hello, 

I just met such issue when creating a cluster, could you please take a look of it? How should I configure docker?
Here is my configuration in /etc/sysconfig/docker:
/etc/sysconfig/docker

Here is the log of munchausen:

time="2016-01-19T11:36:13Z" level=debug msg="[bootstrap] Creating docker client with docker.sock."
time="2016-01-19T11:36:13Z" level=debug msg="[containerhandler] Creating swarm manager container with discovery parameter: _._._._:2376,_._._._:2376,_._._._:2376,_._._._:2376,_._._._:2376,_._._._:2376"
time="2016-01-19T11:36:13Z" level=debug msg="[containerhandler] Couldn't remove container: tmp-swarm-manager: Not found"
time="2016-01-19T11:36:13Z" level=error msg="[containerhandler] Failed to create Swarm manager container: Not found"

**Comment by martonsereg** [comment]
Hi, 
this doesn't look like a munchausen issue, it seems that parameters were not passed correctly to the tool, so this is likely an issue with cloudbreak.

**Comment by ylvmw** [comment]
Does the swarm image need to be installed before calling the bootstrap here?

**Comment by martonsereg** [comment]
I'm not completely sure but I think yes.

**Comment by ylvmw** [comment]
Thanks! Just resolved the issue by install the swarm image manually.
